// Noms en place le 21 septembre 2026. Servis si Notion ne repond pas ou si
// la cle n'est pas encore posee: l'app ne doit jamais rester sans nom.
export const FALLBACK = {
  "Médicaments": "MediSûr",
  "Rendez-vous": "Doctolink",
  "Carnet de santé": "Maple Health",
  "Vaccinations": "Mon Espace Vaccin",
  "Suivi du cycle": "Floé",
  "Symptômes": "Klue",
  "Historique": "Floé Stats",
  "Heure de coucher optimale": "Sleep Circle",
  "Power nap": "Pzazz",
  "Coucher progressif": "Rize",
  "Journal de rêves": "Awaken",
  "Score de récupération": "Whoosh",
  "Jeûne intermittent": "Zerø",
  "Calories & macros": "Yumzio",
  "Calories par photo": "Cal Eye",
  "Scan code-barres santé": "Yuko",
  "Mon frigo": "Fridgy",
  "Liste de courses": "Bringo",
  "Hydratation": "WaterMind",
  "Compléments": "SuppSafe",
  "Allergènes & régimes": "Figue",
  "Programme de sport": "Fitbot",
  "Compteur de pas": "Stepometer",
  "Muscu & progression": "Hevvy",
  "HIIT / Tabata": "TabaTime",
  "Mobilité & stretching": "GOMOB",
  "Streaks & habitudes": "Streakz",
  "Analyse faciale": "Umaxx",
  "Routine skincare": "TrueSkin",
  "Photos avant / après": "Progrez",
  "Mewing & posture": "Mewing Klub",
  "Garde-robe & outfits": "Wearing",
  "Respiration & cohérence": "Breathwerk",
  "Méditation": "Headplace",
  "Sons relaxants": "Endlo",
  "Humeur & gratitude": "Daylia",
  "Détox écran": "Opale",
  "Briefing du matin": "Fabuleux",
  "To-do intelligente": "Todoo",
  "Time-blocking auto": "Structurd",
  "Habit tracker": "Habitly",
  "Focus / Pomodoro": "Forêt",
  "Notes & second cerveau": "Notio",
  "Comptes & dépenses": "Bankino",
  "Budget par enveloppes": "Ynabi",
  "Abonnements": "Pocket Money",
  "Split entre potes": "Quadricount",
  "Objectifs d'épargne": "Kapital",
  "Solde global": "Linxa",
  "Portefeuille": "Finario",
  "Net worth & FIRE": "Kubero",
  "Immobilier": "Horizo",
  "Simulateur fiscalité": "Impôts+",
  "Suivi des candidatures": "Huntly",
  "Générateur de CV": "Zetty",
  "Compétences manquantes": "LinkedUp",
  "Mock interview": "Yoodly",
  "Matching d'offres": "Welcome to the Djob",
  "Langues": "Trilingo",
  "Flashcards": "Anko",
  "Micro-learning du jour": "Headwave",
  "Résumés de livres": "Blinklist",
  "Plan de montée en compétence": "Coursia",
  "Anti-gaspi & péremption": "NoGaspi",
  "Recettes avec les restes": "SuperCuisto",
  "Tâches ménagères": "Sweepo",
  "Mes animaux": "12pets",
  "Maintenance récurrente": "HomeZen",
  "Ma voiture": "Fuelo",
  "Trajets & CO₂": "CityMappr",
  "Où ai-je garé ?": "Park Maps",
  "CRM personnel": "Dexo",
  "Anniversaires & cadeaux": "Hipp",
  "Sorties & events": "Partyful",
  "Coffre-fort documents": "Digicoffre",
  "Échéances": "Papernid",
  "Générateur de courriers": "Lettre-Public",
  "Scan & classement": "Adobo Scan",
  "Mes voyages": "TripUp",
  "Convertisseur": "Xchange",
  "Phrases de voyage": "iTraduis",
  "Traduction": "Goggle Traduction",
  "Suivi des vols": "Flighto"
};
